---
  - name: Check if "Swarm Mode" is enabled.
    shell: docker info
    changed_when: False
    register: docker_info

  - name: get the main swarm manager
    set_fact: swarm_manager={{ hostvars[groups['manager'][0]][ansible_device]['ipv4']['address'] }}

  - name: Start a Swarm
    shell: docker swarm init --advertise-addr {{ swarm_manager }}
    when: "docker_info.stdout.find('Swarm: active') == -1 and inventory_hostname == groups['manager'][0]"

  - name: Get the worker join-token.
    shell: docker swarm join-token -q worker
    delegate_to: "{{ groups['manager'][0] }}"
    changed_when: False
    register: docker_worker_token

  - name: Create overlay network
    docker_network:
      name: ejosh_network
      driver: overlay
    delegate_to: "{{ groups['manager'][0] }}"
    ignore_errors: yes
    #this errors but creates the network

  - name: Join the pending Swarm worker nodes.
    shell: docker swarm join --token "{{ docker_worker_token.stdout }}"
      {{ swarm_manager }}:2377
    when: "docker_info.stdout.find('Swarm: active') == -1
    and 'worker' in group_names"
